In [2]:
# Consider the below code to answer further questions:
import numpy as np
list_ = [ '1','2','3','4','5']
array_list = np.array(object = list_)

In [3]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [4]:

print(f"Data type of list_: {type(list_)}")
print(f"Data type of array_list: {array_list.dtype}")

Data type of list_: <class 'list'>
Data type of array_list: <U1


In [5]:
# list_ is a Python list, which is a built-in Python data structure capable of holding a collection
# of items. Each item in the list can be of any data type, and Python lists are known for their flexibility 
# in holding heterogeneous data.

# array_list, on the other hand, is a NumPy array. NumPy arrays are specialized for numerical computations 
# and are more efficient for mathematical operations than Python lists. The elements of a NumPy array are of a 
# uniform data type. In this specific case, since the elements of list_ are string literals ('1', '2', '3', etc.), 
# array_list will be an array of strings.

In [6]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.

In [7]:
print("Data types in list_:")
for item in list_:
    print(type(item))

print("\nData type of elements in array_list:")
print(array_list.dtype)

Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in array_list:
<U1


In [8]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

In [ ]:
# Will there be any difference in the data type of the elements present in both the variables, list_ and
# arra_list? If so then print the data types of each and every element present in both the variables, list_
# # and arra_list.

In [11]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

print("Data types in list_:")
for item in list_:
    print(type(item))

print("\nData types in array_list:")
for item in array_list:
    print(type(item))


Data types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [12]:
# Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [13]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [14]:

# Finding the shape of num_array
shape_of_array = num_array.shape
print(f"Shape of num_array: {shape_of_array}")

# Finding the size of num_array
size_of_array = num_array.size
print(f"Size of num_array: {size_of_array}")


Shape of num_array: (2, 3)
Size of num_array: 6


In [15]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [21]:
import numpy as np

# Creating a 3x3 array of zeros
data=np.random.randint(0,1,(3,3))
print(data)

zero_array = np.zeros((3, 3))
print(zero_array)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [24]:
import numpy as np

data1=np.diag([1,1,1,1,1,]) 
print(data1)

# Creating a 5x5 identity matrix
identity_matrix = np.eye(5)

print(identity_matrix)


[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
